osx:
	g++ -ansi -pedantic -std=c++11 -Wno-deprecated *.cpp -framework GLUT -framework OpenGL


all:
	g++ -ansi -pedantic -std=c++11 -Wno-deprecated *.cpp -DGL_GLEXT_PROTOTYPES -lglut -lGL -lGLU


clean:
	rm -f *~ *.o a.out
